var car = "Ferrari";
var otherCar = "Mehran";
console.log("Both cars are equal?", car === otherCar);
console.log("Both cars are equal?", car === 'Ferrari');
var name1 = "Ali";
var name2 = "ali";
console.log("Both names are equal?", name1 === 'Ali');
console.log("Both names are equal?", name1 === 'ali');
var age = 20;
console.log("Is age 20?", age === 20);
console.log("Is age 20?", age < 20);
console.log("Is age 20?", age > 20);
console.log("Is age 20?", age <= 20);
console.log("Is age 20?", age >= 20);
var color1 = "Blue";
var color2 = "Black";
console.log("Is color blue?", color1 && color2);
console.log("Is color blue?", color1 || color2);
var games = ["Gta", "CS", "Need for speed", "Assassin"];
console.log("Is Dota in list of gmaes?", games.includes('Dota'));
console.log("Is Gta in list of gmaes?", games.includes('Gta'));
